___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [1]:
import pandas as pd
import numpy as np
import chart_studio.plotly as py
%matplotlib inline

In [2]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

7.0.0

In [3]:
import cufflinks as cf
import plotly.express as px

In [4]:
# For Notebooks
init_notebook_mode(connected=True)

In [5]:
# For offline use
cf.go_offline()

### Fake Data

In [6]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [7]:
df.head()

          A         B         C         D
0  1.338407  0.340535 -2.568822  0.566867
1 -0.205725 -1.786143  2.154179 -0.647327
2  3.584820 -1.299710  0.431859 -0.463091
3  1.347241  1.974708 -0.838648 -0.239351
4  0.031105 -0.046680  0.799306 -0.711031

In [8]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [9]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [10]:
import nbformat
print(nbformat.__version__)

5.11.1

In [17]:
#df.iplot()
fig = px.line(df)
fig.show()

In [11]:
import plotly.express as px

fig = px.scatter(df, x='A', y='B')
fig.update_traces(marker=dict(size=10))
fig.show()

## Bar Plots

In [14]:
#df2.iplot(kind='bar',x='Category',y='Values')
fig = px.bar(df2,x='Category', y='Values')
fig.show()

In [22]:
#df.count().iplot(kind='bar')
fig = px.bar(df.sum())
fig.show()

In [23]:
fig = px.bar(df.count())
fig.show()

## Boxplots

In [25]:
#df.iplot(kind='box')
fig = px.box(df)
colors = ['red', 'blue', 'green', 'orange']

for i, box in enumerate(fig.data):
    box.marker.color = colors[i]
fig.show()

## 3d Surface

In [28]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
# Use scatter_3d for individual points
fig = px.scatter_3d(df3, x='x', y='y', z='z', color='z',color_continuous_scale='rdylbu')
fig.show()

In [ ]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
# df3.iplot(kind='surface',colorscale='rdylbu')

In [29]:
import plotly.graph_objects as go

df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})

# Pivot data into a 2D matrix structure where columns are X, index is Y, and cells are Z
# Note: For this small sample, many intersections will be NaN/empty unless properly gridded
grid_df = df3.pivot(index='y', columns='x', values='z')

# Generate the 3D surface plot
fig = go.Figure(data=[go.Surface(
    x=grid_df.columns, 
    y=grid_df.index, 
    z=grid_df.values, 
    colorscale='rdylbu'
)])

fig.show()

## Spread

In [50]:
df[['A','B']].iplot(kind='spread')

## histogram

In [33]:
fig = px.histogram(df['A'])
fig.show()

In [56]:
df['A'].iplot(kind='hist',bins=25)

In [60]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [13]:
df.scatter_matrix()

# Great Job!